### ISSUE TITLE
Add asynchronous worker support for the HTML5 target

### ISSUE THREAD

**Issue by jgranick** [openfl/lime#1081]
`BackgroundWorker` as well as `ThreadPool` use a synchronous mode on HTML5, but these could be made to use web workers on HTML5

https://stackoverflow.com/a/37156020

Depending on the performance of web workers, it may be preferable to consider whether one or both of the above APIs should also have a way to use them synchronously by choice, if web workers end up being too expensive

**Comment by player-03** [comment]
`ThreadPool` won't work in HTML5, because [you can't pass functions as a message](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm). This behavior is required by [Future](https://github.com/haxelime/lime/blob/8c9808b038ea06ea1f8c8c1ffb4a6d01d43c7972/src/lime/app/Future.hx#L82) at the very least.

(Yeah, I know only Firefox uses the `structuredClone()` function, but the error also happens in Chrome, so whatever function it uses imposes the same restriction.)

Maybe we can pass a string and then call `Function()`...

**Comment by barisyild** [comment]
HTML5 workers does not support shared memory usage.
I know that it is possible to send byte data only with SharedArrayBuffer.

Note: wasm has thread support but unfortunately does not share memory like worker.

**Comment by player-03** [comment]
Oh yeah, forgot to mention that, but the lack of shared memory is the other problem with `ThreadPool`. The current implementation relies on a shared `Deque` - the main thread adds a task to this queue, and whichever thread becomes available next gets to handle it.

Workaround is obvious but annoying: the main thread will have to handle all scheduling. Keep track of which threads are busy and which are done, and assign incoming tasks to available threads.

**Comment by player-03** [comment]
After significant work, [I've concluded that web workers are incompatible with Lime's mission](https://player03.com/development/on-starting-over/). (Long post, so [click here if you just care about the reasoning](https://player03.com/development/on-starting-over/#web-worker-assumption).)

As an alternative, I propose a single-threaded async mode. Details to come.

**Comment by player-03** [comment]
This didn't get closed automatically? Whoops.
