### ISSUE TITLE
Access to raw png

### ISSUE THREAD

**Issue by delahee** [openfl/lime#114]
In the lime context, it would preferable to access the raw png loading api since on most gl api, we can perform loading directly to RGBA or BGRA rather than using the odd ARGB adobe feature.

**Comment by jgranick** [comment]
There are now PNG/JPG classes in the Lime API, if you think it would be good to be able to decode with options (such as specifying the color order), then please feel free to look at doing a pull request for that. Otherwise, the color order now should be consistent with the rest of the Lime ImageBuffer/Image API, which should allow for direct upload to the GPU without flipping the pixels :smile:
