### ISSUE TITLE
Native Curl slow loading speed

### ISSUE THREAD

**Issue by guruas3** [openfl/lime#1276]
I've mentioned this problem several times in community chat.

After 7.0.0 release with curl refactoring to curl multi the loading speed is considerably slower for native targets and depends on application FPS and curl multi timer delay https://github.com/openfl/lime/blob/develop/src/lime/_internal/backend/native/NativeHTTPRequest.hx#L326

I've done a simple project to easily test it.
Here are my results:

Loading 5 mb image with URLLoader

HTML5 before and after 7.0.0: full internet speed (in my case ~0.7 seconds ~ 80 mbps)
Native before 7.0.0:  windows build full internet speed( in my case 0.7-1 seconds ~ 80 mbps)
Native after 7.0.0: throttling internet speed depending on FPS and `multiTimer` delay
		
- with 30 fps it loads with any internet speed in ~12 seconds ~= 3-4 mbps
- with 60 fps( and multiTimer(14) ) in 6 seconds ~= 7-8 mbps
- by increasing fps to 120 and multiTimer(7) the loading time goes down ~ 3 seconds but still slower than HTML5 or before 7.0.0 lime

[CurlSlowSpeed.zip](https://github.com/openfl/lime/files/2733105/CurlSlowSpeed.zip)

**Comment by jgranick** [comment]
Thank you for the test!

I see times in HTML5 that average around 1.5 seconds here, and once as high as 3 seconds. On first run, I was getting times of about 9-10 seconds at 30 FPS. I've made a number of changes to help things along:

https://github.com/openfl/lime/commit/464dc88c447866e2f12368f1b7a7948bf8e27b9a

Now I get about 6 seconds at 30 FPS, and about 3.3 seconds at 120 FPS.

The only solution (I think) to get lower times is to sleep less. We need to work on a solution lower down in the main loop to maybe sleep less if network transfers are running, and to fire that at a faster rate than the application frame rate. Either way, I think this is a good start

**Comment by guruas3** [comment]
Thank you Joshua for the quick fix but it doesn't change the loading times for me.

I still get around 6 seconds on native with 60 FPS. The only thing that has changed is that you can get faster loading by just changing application FPS without changing manually `multiTimer` in NativeHttpRequest. But my app won't handle 120 FPS. So if you can find a better solution that is not coupled with FPS and have similar loading times as with lime <7.0.0 that would be great.

HTML5 is not depending on NativeHttpRequest if i'm right, so i get full loading speed with ~ 1 second load.

So native is loading 6 times slower for 5 mb files and maybe even slower for bigger files. My app loads files around 10+ mb so it's not usable anymore with these loading times. I'm using custom lime and openfl versions and can't use latest versions because of several bugs like this one.

Thank you

**Comment by jgranick** [comment]
The next step would be to work with the update code, here, to update the cURL Multi process more often, while still maintaining the proper frame rate:

https://github.com/openfl/lime/blob/develop/project/src/backend/sdl/SDLApplication.cpp#L855

I released a new version of Lime yesterday, so now our other fixes should be out and stable, so we could try and focus on something more significant like this.

The other approach would be to use cURL (not Multi) for a faster download in another thread. The catch is that it will block until it finishes, so no progress events. That was the trade-off for fixing Haxe garbage collection / thread related issues. You cannot allocate Haxe objects in a process that might not respect when the garbage collector tells all threads to stop. There may be a way to "flush" progress events in a way that doesn't hurt the garbage collector, but nevertheless its a complicated problem.

Multi is always slower than a single blocking cURL thread, in my experience, which is why we designed our networking to use that approach at first. However, we've already seen that calling the Multi update more often can speed up our download, now, so it's just time to take it the next step

**Comment by guruas3** [comment]
Seems like simple cURL (not multi) is not a way to go. So we need to decouple calling `multi.perform` with `haxe.Timer` as the later one is coupled with FPS.

I've bumped into this while reading libcurl docs: 

> Your application can acquire knowledge from libcurl when it would like to get invoked to transfer data, so that you don't have to busy-loop and call that curl_multi_perform(3) like crazy. 

> Your application extracts info from libcurl about when it would like to get invoked to transfer data or do other work. The most convenient way is to use curl_multi_wait that will help you wait until the application should call libcurl again. The older API to accomplish the same thing is curl_multi_fdset that extracts fd_sets from libcurl to use in select() or poll() calls in order to get to know when the transfers in the multi stack might need attention. Both these APIs allow for your program to wait for input on your own private file descriptors at the same time curl_multi_timeout also helps you with providing a suitable timeout period for your select() calls.

We can try to implement `curl_multi_wait ` and see if it improves loading speed

**Comment by jgranick** [comment]
I got it down to about 1.8 seconds here by using a background thread, but now I need to deal with new problems created by the added multi-threading. Still working on it

**Comment by jgranick** [comment]
There is a commit here to help with cURL cleanup:

https://github.com/openfl/lime/commit/e582f8f6b40d99a23a7611cb4b00b950cd1e8d5e

Then https://github.com/openfl/lime/commit/e582f8f6b40d99a23a7611cb4b00b950cd1e8d5e should add a thread to manage cURL Multi using the `wait` command. When I first build, I get a longer network time (around 6-8 seconds) but subsequent builds take about 2 seconds. I suspect (could be wrong?) the delay is caused by Windows' virus protection.

In my experience, cURL Multi is slower than individual cURL requests. We could use a `ThreadPool` and manage distinct cURL instances, now, but that won't work with progress events. The above changes should keep Multi running as fast as it wants, while still keeping us on the good side of HXCPP's GC, and while still giving us progress events. This seems like a good improvement, but try it out and let me know how it goes :smile:

**Comment by guruas3** [comment]
This is some good progress! The loading time is 0.8-1.2 seconds so quite similar to what it was before lime 7.0.0. It's still slightly slower for 10mb and up files 2.6s vs 2.0s (lime 7.0.0) But these are just minor things compared to what it was before the fix. So this bug can be considered closed.

But the other bug with curl popped up again https://github.com/openfl/lime/issues/1232
You can try the attached project to re-create the issue. ( next requests doesn't load at all)

Thank you for your work Joshua!

**Comment by jgranick** [comment]
Thanks for the feedback! The thread sync, I think, introduces some delay depending on the timing, though you could experiment with using a shorter `multi.wait` timeout, it might tighten this up?

Thanks for pointing out this issue, I found a way to make sure we trigger the multi thread again if there's still a pending request in the queue. It looks good now on my end, let me know what you find :smile:
