### ISSUE TITLE
Howl and pako ReferenceError

### ISSUE THREAD

**Issue by peteshand** [openfl/lime#1304]
Has there been a change to the order in which Howl and pako are loaded in the latest Lime?

I've started to get a heap of Reference Errors today

Uncaught ReferenceError: Howl is not defined
and
Uncaught ReferenceError: pako is not defined

Seems to be some type of race condition as it's only happening about 50% of the time.
Is anyone else having the same issue?

**Comment by jgranick** [comment]
Does it make a difference if you edit this file (templates/html5/output.js) and move the "embeddedLibraries" section to the top?

https://github.com/openfl/lime/blob/develop/templates/html5/output.js

We started putting Howler and pako into the ApplicationMain.js instead of copying them separately

**Comment by TomByrne** [comment]
Including these files as part of the Lime js output seems to be problematic when running in electron.
This is because most js libraries detect whether they're running in a 'module' based environment (e.g. node/electron/webpack) by checking whether the global props 'module', 'exports' or 'define' exist (mostly using 'exports').
If so, then the library will treat the `module.exports` object as it's own export space, potentially totally clearing exports and populating it with it's own methods (as pako does - `module.exports=f()`). It also will often not include it's own namespace wrapper in this mode, assuming that webpack/node will do that, this is a problem because pako's functionality (for example), ends up at `module.exports.inflateRaw`, with no `pako` wrapper.
This means that js libraries included through Lime (and running in electron) will be adding their functionality to the same object, in same cases removing functionality from other included libs.

The resolution to this that I've found is to 'fool' the libraries into thinking that they're running in a regular old browser context, where typically they'll add their functionality into a namespace object on the global/window object (e.g. window.pako = {...}). This is done by running them in a function that first has: `var module=undefined,exports=undefined,define=undefined;`.

Obviously this isn't guaranteed to work for all libraries but was working for us with Howler/pako/FileSaver.
Has also been tested after webpacking, which wasn't working since 7.3.

Pull Request: https://github.com/openfl/lime/pull/1308

**Comment by jgranick** [comment]
How can I reproduce this issue?

`lime test electron` appears to work fine using the latest Lime and the Pirate Pig demo -- no Pako or Howler issue.

Does this occur when running another command to package the application?

**Comment by peteshand** [comment]
Thanks for looking into this Joshua. After a bit more investigation I think it's related to some auto reload logic being fired to early
