### ISSUE TITLE
More robust target detection in XML

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#1394]
Currently, HTML5 builds break if there's an env variable called `hl` due to `if="hl"` in the XML:

![](https://i.imgur.com/eHzGp8J.png)

@jgranick had some ideas to make this more robust:

>but perhaps we should just define "target-" defines instead
>or "target:"
>`if="target-hl"` or `if="target:hl"`

**Comment by player-03** [comment]
Haven't tested it, but from the code I'm pretty sure you can write `if="${targetType==hl}"` if you want certainty. Except it only works for XML projects, and HXP projects are out of luck.

I think what needs to happen is `ProjectXMLParser.initialize()` needs to go in `HXProject` so that all projects will play by the same rules. Edit: done as of 6725825469b8cb3113090daeb837f7a72bdc6d9e.
