### ISSUE TITLE
Could not find haxelib "Lime", does it need to be installed?

### ISSUE THREAD

**Issue by nycolexavier** [openfl/lime#1479]
![image](https://user-images.githubusercontent.com/74930052/135456244-d7a4a015-cb7f-4161-86f4-7c0ce62b9529.png)

version haxe: 4.1.4

**Comment by player-03** [comment]
Also try `haxelib run lime` instead of just `lime`. Maybe there's a difference there. If so, try `where lime` to figure out what's causing the problem. Then delete that executable and run `haxelib run lime setup` to recreate it.

In any case, it's a strange error. If the easy options don't work, you probably have to reinstall Lime and/or Haxe.

Closing this on account of you've probably moved on by now.
