### ISSUE TITLE
HXP: Icon behavior inconsistent with XML

### ISSUE THREAD

**Issue by MasterEric** [openfl/lime#1508]
When generating icons for executables (at least on Windows), the behavior is not consistent between XML and HXP projects, to where incorrect icons are being displayed on my project.

In XML, using the `<icon>` tags result in the following (I added a print call to `IconHelper#createWindowsIcon`):

```
IconHelper.createWindowsIcon([
  { path => C:/HaxeToolkit/haxe/lib/flixel/4,10,0/assets/images/logo/HaxeFlixel.svg, width => 0, size => 0, height => 0 },
  { path => art/icon8.png, width => 8, size => 8, height => 8 },
  { path => art/icon16.png, width => 16, size => 16, height => 16 },
  { path => art/icon32.png, width => 32, size => 32, height => 32 },
  { path => art/icon64.png, width => 64, size => 64, height => 64 },
  { path => art/icon128.png, width => 128, size => 128, height => 128 },
  { path => art/icon256.png, width => 256, size => 256, height => 256 },
  { path => art/icon512.png, width => 512, size => 512, height => 512 },
  { path => art/iconOG.png, width => 0, size => 0, height => 0 }
], export/debug/windows/bin/icon.ico)
```

Of note is that the internal default icon, `HaxeFlixel.svg`, is included first, but is then overlapped by the `art/icon` files.

In HXP, using the `icon.push` function results in the following:

```
IconHelper.createWindowsIcon([
  { path => art/icon8.png, width => 8, size => 8, height => 8 },
  { path => art/icon16.png, width => 16, size => 16, height => 16 },
  { path => art/icon32.png, width => 32, size => 32, height => 32 },
  { path => art/icon64.png, width => 64, size => 64, height => 64 },
  { path => art/icon128.png, width => 128, size => 128, height => 128 },
  { path => art/icon256.png, width => 256, size => 256, height => 256 },
  { path => art/iconOG.png, width => 0, size => 0, height => 0 },
  { path => C:/HaxeToolkit/haxe/lib/flixel/4,10,0/assets/images/logo/HaxeFlixel.svg, width => 0, size => 0, height => 0 }
], export/debug/vanilla/x64/windows/bin/icon.ico)
```

The `HaxeFlixel.svg` icon (provided by the `include.xml` from OpenFL) is added after the HXP finishes processing. The result is that when building with HXP, I cannot override the icon properly and it always appears with the HaxeFlixel default icon.

I believe I may be able to circumvent this by using an OpenFL template to override the `include.xml` but this issue should be resolved the proper way.

**Comment by player-03** [comment]
> Of note is that the internal default icon, `HaxeFlixel.svg`, is included first, but is then overlapped by the `art/icon` files.

Interesting. [`IconHelper` loops through all icons in order without a `break` statement](https://github.com/haxelime/lime/blob/0c163a80e76d9515d272c5e065996ac74d498644/src/lime/tools/IconHelper.hx#L282-L288), so it'll only use the final match. Tiny bit inefficient, but still correct.

> The `HaxeFlixel.svg` icon (provided by the `include.xml` from OpenFL) [...]

Technically [Flixel's include.xml](https://github.com/HaxeFlixel/flixel/blob/c53bbb5e10c354bf5c032fb4cdfd1807a0d09271/include.xml#L5), but close enough.

> [...] is added after the HXP finishes processing.

Yep. The HXP file gets processed on [line 597](https://github.com/haxelime/lime/blob/f6fb941c997716094d792e60f7ee84d58ebd1ce3/src/lime/tools/HXProject.hx#L597), meaning it fully runs and returns. Afterwards on [line 647](https://github.com/haxelime/lime/blob/f6fb941c997716094d792e60f7ee84d58ebd1ce3/src/lime/tools/HXProject.hx#L647), its Haxelib dependencies get parsed and merged.

For comparison, when you specify a `<haxelib />` tag in `ProjectXMLParser`, it [immediately parses and merges that library](https://github.com/haxelime/lime/blob/f110d52e5a17e17422183c7dd90e9dfdc1f85782/src/lime/tools/ProjectXMLParser.hx#L1265-L1280).

Speaking of merging, let's take a moment to look at the [`merge()`](https://github.com/haxelime/lime/blob/f6fb941c997716094d792e60f7ee84d58ebd1ce3/src/lime/tools/HXProject.hx#L834) function. It's called any time one project imports another, and among other things, it [concatenates the icon lists](https://github.com/haxelime/lime/blob/f6fb941c997716094d792e60f7ee84d58ebd1ce3/src/lime/tools/HXProject.hx#L884), placing imported icons at the end.

> The result is that when building with HXP, I cannot override the icon properly and it always appears with the HaxeFlixel default icon.

Which isn't surprising given the code we went over. As for fixing it, there are a couple potential approaches.

One is to exploit the fact that `merge()` calls [`concatUnique()`](https://github.com/haxelime/hxp/blob/526ea0379d00b32095df8e69b7aed380297fcf27/src/hxp/ArrayTools.hx#L26) instead of just `concat()`. If you insert the HaxeFlixel logo at the beginning of the array, then `concatUnique()` will see it there and not add it again... or so you'd hope. Sadly, [`concatUnique()` defaults to the `==` operator](https://github.com/haxelime/hxp/blob/526ea0379d00b32095df8e69b7aed380297fcf27/src/hxp/ArrayTools.hx#L59), which won't recognize the match. (There is a `key` parameter, but it's unused because no single key would be enough.) This could be made to work, but doesn't yet.

A second is to say "if you can't beat them, join them." Make a small Haxelib containing your icons, and include that after Flixel.

A third is to merge the library manually. This is akin to how `ProjectXMLParser` instantly merges each Haxelib, allowing you to add your own icons afterwards. You can either copy the code from `ProjectXMLParser` (making sure _not_ to add it to `haxelibs`), or you can call `HXProject.processHaxelibs(this, HXProject._userDefines)` (which will use and then clear `haxelibs`). Either way, Flixel will be done adding icons, so you can add yours no problem.

Fourth, perhaps `processHaxelibs()` would pass an argument to `merge()` that swapped the order of all array concatenations, meaning new array entries would be added to the start instead of the end. But this would take a lot of code and could cause side effects, so I doubt it's worth it.

Fifth, you could ask the Flixel devs to add `unless="SUPPRESS_FLIXEL_ICON"` to their icon tag.

Since option 3 most closely emulates project.xml, I'd suggest trying that.

> I believe I may be able to circumvent this by using an OpenFL template to override the `include.xml` but this issue should be resolved the proper way.

Templates only apply to files that get copied into Export/[PLATFORM]/bin. Project/include files are used as-is.

**Comment by MasterEric** [comment]
Thank you for the great explanation!

When investigating the suggested solution (option 3, merge the libraries manually), I found some obstacles.

Firstly, it appears that `HXProject.processHaxelibs` does not fully clear the list of haxelibs. Rather, it clears the list, then readds them as it is processing. This meant I received an error (since the haxelib was being processed twice). My solution was to clear the list myself after processing.

However, this raised a second issue. On [this line of Flixel's include file](https://github.com/HaxeFlixel/flixel/blob/c53bbb5e10c354bf5c032fb4cdfd1807a0d09271/include.xml#L25) it references a macro, and it appears this is called after HXP in the build process.

If I clear the haxelib from the list of haxelibs after processing, this macro fails with the error `(unknown) : Type not found : flixel.system.macros.FlxDefines`. If I don't clear the haxelib from the list, the build fails because it is merged twice.

Attempting to call the relevant macro manually in my HXP fails with:

```C:\Users\Eric\AppData\Local\Temp/temp_14254942/Project.hx:433: characters 3-34 : Type not found : flixel.system.macros.FlxDefines```

I'm going to pursue the fifth option for now unless there is a fix for this.

**Comment by player-03** [comment]
Oh, of course. I missed the line where it repopulated the array and thought therefore it was safe to clear it. But no, the array is actually used twice. Once to merge the projects, and then [again to add to `templateContext`](https://github.com/haxelime/lime/blob/f6fb941c997716094d792e60f7ee84d58ebd1ce3/src/lime/tools/HXProject.hx#L1203-L1339). This loop does two important things:

1. [Sets `-Dflixel=4.10.0`](https://github.com/haxelime/lime/blob/f6fb941c997716094d792e60f7ee84d58ebd1ce3/src/lime/tools/HXProject.hx#L1291).
2. [Adds the project root as a class path](https://github.com/haxelime/lime/blob/f6fb941c997716094d792e60f7ee84d58ebd1ce3/src/lime/tools/HXProject.hx#L1277-L1279) (you'll note that Flixel's include.xml has no `<source />` tag; this is because it only needs the root). That would explain your situation - without the class path, it can't find `FlxDefines`.

(In case you're wondering how all this is related to `templateContext`, once it finishes building the `compilerFlags` variable, it sets `context.HAXE_FLAGS = "\n" + compilerFlags.join("\n")`. Then [the HXML file template](https://github.com/haxelime/lime/blob/develop/templates/cpp/hxml/release.hxml#L1) includes `HAXE_FLAGS` verbatim.)

Ok, clearly this is why you're discouraged from calling `processHaxelibs()`. All Haxelibs must remain in the list, and any Haxelibs that remain in the list will be processed for you, and it's unsafe to process them twice.

As for solutions, hmm. There is a way forward with option 3: keep a list of processed Haxelibs so as not to process them twice, though I'll admit it could be overkill for such a niche case. Or we could look for indicators that already exist. Speaking of, what error did you get?

**Comment by MasterEric** [comment]
> Speaking of, what error did you get?

The error I got was something along the lines of "flixel_beep_ogg already defined". When I opened up the ManifestResources.hx file the error was pointing to, I found the asset files provided by HaxeFlixel were being included in the file twice.

**Comment by player-03** [comment]
Yeah ok, that isn't going to work as an indicator. None of these are ideal...

**Comment by player-03** [comment]
Give my new pull request a try when you get time. Given that you're supplying exact-size icons, it should work without any changes to Flixel's include.xml.

Though as things stand, your 0-size PNG will be completely ignored. I changed it so that instead of assuming 0-size icons are SVGs, it checks the extension. Do you have a use case for that 0-size PNG, or did you just include it for completeness?
