### ISSUE TITLE
VorbisFile.cpp : free(ptr) created with ptr = new is invalid

### ISSUE THREAD

**Issue by mgambrell** [openfl/lime#1556]
This should not be free, it should be delete (since it was allocated with new):
https://github.com/openfl/lime/blob/4f83af5848d1655b810705ba1b63d6cd0738ee15/project/src/media/codecs/vorbis/VorbisFile.cpp#L84

Similar problems here:
https://github.com/openfl/lime/blob/4f83af5848d1655b810705ba1b63d6cd0738ee15/project/src/media/codecs/vorbis/VorbisFile.cpp#L157

Same problem in VorbisFile::FromFile

probably any other free() in this source code file is the same problem

This causes actual crashes in environments with unusual memory managers

**Comment by mgambrell** [comment]
I've tested it. I can't test a PR because I have vendored this library, heavily modified it.

**Comment by player-03** [comment]
That isn't actually a problem using Git branches. Make one branch for your personal modifications, and one for the changes you want to submit.

If the problem is that you want to keep your modifications private, you could make two entire forks, one public and one private. This will require either (1) [unforking your existing repo](https://ralphjsmit.com/unfork-github-repo) or (2) [creating a mirror](https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository), manually reverting the fork, and then making the fork public. I know both options sound like work, but it'll pay off. If you're going to keep using Lime, you'll run into more cases like this, where you'll want to have the ability to submit pull requests.

**Comment by mgambrell** [comment]
The problem isn't with the bookkeeping, the problem is that I simply don't know how to set up a new haxe project and write a test which covers this case. I can only test in my private environment.

**Comment by player-03** [comment]
That isn't required to submit a pull request here. Appreciated, yes, but you can submit it and let someone else test.
