### ISSUE TITLE
lime test windows problems - "Uncaught exception - std@sys_file_type"

### ISSUE THREAD

**Issue by Marker228** [openfl/lime#1572]
When I write the command "lime test windows" I get an error every time

Called_` from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 1703
Called from lime/tools/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 50
Called from lime/tools/ProjectXMLParser.hx line 2043
Called from lime/tools/ProjectXMLParser.hx line 1528
Called from lime/tools/ProjectXMLParser.hx line 608
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 709
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 69
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 60
Uncaught exception - std@sys_file_type

What should I do?

**Comment by joshtynjala** [comment]
I think it means that there is something wrong with the path to one of your assets specified in project.xml.

**Comment by Marker228** [comment]
The problem is that before the error pops up, I get another about lime (I use Visual Code):
"Lime completion setup failed. Is the lime command available? Try running "lime setup" or changing the "lime.executable" setting.";
  And:
"The XML language server crashed 5 times in the last 10 minutes. The server will not be restarted.".

**Comment by player-03** [comment]
All those error messages are probably caused by the same underlying issue: there's an inaccessible file or folder in one of your asset directories.

It's impossible to tell from the error which file or folder this is, but the easiest way to find out is to insert a `trace()` statement right above ProjectXMLParser.hx line 709.

```diff
		for (file in files)
		{
+			trace(path + "/" + file);
			if (FileSystem.isDirectory(path + "/" + file))
			{
```

Then run `lime rebuild tools` before recompiling your app. (If you forget this, it won't print.)

Once you find the file, make sure to remove the `trace()` statement and run `lime rebuild tools` again.
