### ISSUE TITLE
The app icon isn't changing?

### ISSUE THREAD

**Issue by MAJigsaw77** [openfl/lime#1576]
I'm using this code
```xml
<icon path="pathtoicon.png" priority="-10" />
```
But the icon isn't changing, what show i do?

**Comment by player-03** [comment]
I take it you copied that from Flixel? Flixel sets a very low priority so that you can override their icon. The trick is to give your icon a higher priority, such as 0. (That's also the default value. You can leave out `priority` entirely for the same result.)

**Comment by MAJigsaw77** [comment]
Let me try

**Comment by MAJigsaw77** [comment]
@player-03 nothing changed
![Screenshot_2022-09-01-08-55-51-890_com google android packageinstaller](https://user-images.githubusercontent.com/77043862/187842067-8b6ee105-acaa-4892-af02-1490a2e9d93c.jpg)

**Comment by MAJigsaw77** [comment]
It's basically the same.

**Comment by player-03** [comment]
Is there some reason you can't use an SVG icon?

**Comment by MAJigsaw77** [comment]
It's png

**Comment by MAJigsaw77** [comment]
It wasn't like this before the update

**Comment by MAJigsaw77** [comment]
What should i do?

**Comment by player-03** [comment]
Ok, so this was in fact due to a breaking change. A change I submitted, as it happens.

Lime generally prefers SVGs over PNGs, and I think that makes sense. SVGs can scale to any size without loss of quality, making them great for icons. The problem is that Lime prefers lower-priority SVGs over higher-priority PNGs, unless you explicity set the PNG's `size` property. (And since Lime creates several icons, you have to set several sizes. The exact sizes are target-dependent and not documented.)

Not a great situation. I'll go propose a fix.

**Comment by MAJigsaw77** [comment]
@player-03 
![Screenshot_2022-09-01-20-29-49-061_com google android packageinstaller](https://user-images.githubusercontent.com/77043862/187978416-3125a854-69e4-436f-88a8-fd2436a219f0.jpg)

**Comment by MAJigsaw77** [comment]
The pull request changes nothing.

**Comment by joshtynjala** [comment]
@MAJigsaw77 did you rebuild lime tools?

**Comment by MAJigsaw77** [comment]
I added the file to source folder.

**Comment by MAJigsaw77** [comment]
We can't just to revert the commit that brokes everything?

**Comment by player-03** [comment]
To rebuild the tools, run `lime rebuild tools`.

**Comment by MAJigsaw77** [comment]
That isn't helping, I think I'll just go back to lime 7.9.0.

**Comment by Dimensionscape** [comment]
> 

No worries. This was a huge update so there are bound to be some hiccups. We'll try to put out a patch version to fix a couple things like this soon.

**Comment by MAJigsaw77** [comment]
Thanks, good luck on fixing them 👍

**Comment by player-03** [comment]
Looks like Flixel hasn't released an update yet. If you're using the Haxelib version of Flixel, then their icon will still have priority 0, instead of -10. Therefore to beat their priority, you'll either have to set `priority="1"` or higher, or equivalently place your `<icon />` tag after the `<haxelib name="flixel" />` tag.

Once you do either of those, you also have to delete export/html5/bin/favicon.png before Lime will regenerate the icon.

**Comment by Luminus71** [comment]
So, this problem is happening again, the icon isn't refreshing and it's stuck in a haxe default icon, is there's a way to how to fix that problem?
![image](https://user-images.githubusercontent.com/110564857/204186682-2a75c1eb-3714-454f-ae40-3e823177cdfd.png)

**Comment by player-03** [comment]
Until the 8.0.1 patch comes out, you'll have to use the Git version of Lime.

```cmd
> haxelib git lime https://github.com/openfl/lime.git
> lime rebuild tools
```
