### ISSUE TITLE
creating an instance of java object via jni fails

### ISSUE THREAD

**Issue by Sirox228** [openfl/lime#1592]
i was making an extension for kizzy-rpc to use it in my app, because there's no other ways to make discord rpc on android, kizzy-rpc is written in java and uses java-websocket, so i need to make it via jni, i tried to do so, but faced an issue.
I made a simple class that uses jni for this (only constructor shown there):
```
package kizzy;

import lime.system.JNI;

@:access(lime.system.JNI)
class KizzyRPCservice {
	
	var service:Dynamic;
	
	public function new() {
		service = JNI.createStaticMethod('org/haxe/extension/KizzyRPCservice', 'create', '()Lorg/haxe/extension/KizzyRPCservice;');
	}
}
```
java code of this function:
```
public static KizzyRPCservice create() {
    	return new KizzyRPCservice();
}
```
then, i called methods of that java class like this:
```
public function setToken(token:String):KizzyRPCservice
{
	JNI.callMember(JNI.createMemberMethod('org/haxe/extension/KizzyRPCservice', 'setToken', '(Ljava/lang/String;)Lorg/haxe/extension/KizzyRPCservice;'), service, [token]);
	return this;
}
```
but whenever i tried to call it, nothing was happening in app and this was appearing in logs:
```
Lime     :  lime_jni_call_member - invalid this
```
i searched what is that and found it in `project/src/system/JNI.cpp` in lime source code:
```
value lime_jni_call_member (value inMethod, value inObject, value inArgs) {

	JNIMethod *method;
	jobject object;

	if (!AbstractToObject (inMethod, method)) {

		ELOG ("lime_jni_call_member - not a method");
		return alloc_null ();

	}

	if (!AbstractToJObject (inObject, object)) {

		ELOG ("lime_jni_call_member - invalid this");
		return alloc_null ();

	}

	return method->CallMember (object, inArgs);

}
```
it seems that for some reason, it can't make JObject from `service` variable, then i thought that maybe i need to call static method for creating java `KizzyRPCservice` object and put result of the function into `service` variable like this:
```
public function new() {
	var serviceJava:Dynamic = JNI.createStaticMethod('org/haxe/extension/KizzyRPCservice', 'create', '()Lorg/haxe/extension/KizzyRPCservice;');
        service = serviceJava();
}
```
but this one resulted in:
```
Uncaught Error: JNI Exception
```
and the only `called from` thing there that can say something is `kizzy/KizzyRPCservice.hx (line 12)` which is:
```
service = serviceJava();
```

i don't know why it don't want to work, as i know, it should work with putting `JNI.createStaticMethod(....)` into a dynamic variable and then calling members from that variable.

if you need to see full source code of the extension, see `hx-kizzy` repository in my profile

**Comment by player-03** [comment]
Your first implementation was incorrect; you can't pass `service` as the `this` argument since it's a function. Gotta call it to get the instance.

---

Since your second implementation calls the function, it ought to work as far as I can tell.

IIRC, "JNI Exception" is a catch-all message indicating an error at some point during the JNI call, which could easily be an error in the Java code. Try looking earlier in the log for a Java error.

Or forget calling from Haxe at all: try calling `new KizzyRPCService()` in your extension's `onCreate()` listener. If that fails too, you'll know for sure where the error is.

---

Also see my comment on #1566 for a way to call constructors directly. I don't think it'll fix this, but it'll make for slightly cleaner code.

**Comment by player-03** [comment]
Closing because this only ever affected one person, and that person has presumably solved it.
