### ISSUE TITLE
Support for notch displays in mobile?

### ISSUE THREAD

**Issue by MAJigsaw77** [openfl/lime#1606]
This might be useful in games for example.

**Comment by joshtynjala** [comment]
Adobe AIR 50 has a new `safeArea` API in `flash.display.Screen`

https://airsdk.dev/reference/actionscript/3.0/flash/display/Screen.html#safeArea

It would be useful to expose this information in Lime so that OpenFL can implement the same API.

I wonder if any newer versions of SDL expose the safe area?

In the meantime, this extension may be useful:

https://github.com/HaxeExtension/extension-safearea

**Comment by MAJigsaw77** [comment]
👍

**Comment by joshtynjala** [comment]
Based on some quick research, SDL does not seem to have an API for notch/safearea yet.

Here's their open issue: libsdl-org/SDL#3243

**Comment by MAJigsaw77** [comment]
By modifying GameActivity from the android template i could get a some results but the offsets doesn't seem so accurate.

![Screenshot_20240609-081415](https://github.com/openfl/lime/assets/77043862/54c30d85-8bee-4606-8c92-f87f095f84ac)
![Screenshot_20240609-081411](https://github.com/openfl/lime/assets/77043862/b0aa4d5e-f4be-4e9e-8adb-12c92d220e08)
![Screenshot_20240609-081337](https://github.com/openfl/lime/assets/77043862/ad8bd7fb-72ea-4ad5-b564-ceb061b59134)

This is the code i used in any case.

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P)
{
	getWindow().getAttributes().layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;
}
```

**Comment by player-03** [comment]
This should be solved as of the latest release.

https://github.com/openfl/openfl/blob/6388ba3b8a9bb3cb80c95bf19c250c00a468a941/src/openfl/display/Screen.hx#L76-L86

https://github.com/openfl/lime/blob/af2299670ff219885d16a5c2f8eed9d1bd5d9c03/src/lime/system/Display.hx#L43-L48
