### ISSUE TITLE
[ISSUE] AssetsMacro "Too many arguments"

### ISSUE THREAD

**Issue by TechnikTil** [openfl/lime#1870]
When I try to compile with Github Actions, I keep getting this error:

```
/home/runner/work/TechNotDrip-Engine/TechNotDrip-Engine/.haxelib/lime/8,2,1/src/lime/_internal/macros/AssetsMacro.hx:36: characters 32-39

 36 |    : macro super(bytes.length, bytes.b);
    |                                ^^^^^^^
    | Too many arguments

/home/runner/work/TechNotDrip-Engine/TechNotDrip-Engine/.haxelib/lime/8,2,1/src/lime/_internal/macros/AssetsMacro.hx:41: lines 41-44

 41 |    {
 42 |     var bytes = haxe.Resource.getBytes(resourceName);
 43 |     $superCall;
 44 |    }
    |
    | Missing super constructor call
```

[Here is a link to the latest run with this error.](https://github.com/TilNotDrip/TechNotDrip-Engine/actions/runs/12202907410/job/34044690063)

**Comment by TechnikTil** [comment]
#1785 
Just found a duplicate, my bad

**Comment by ACrazyTown** [comment]
Are you using Haxe 5?

**Comment by player-03** [comment]
Even if they were, the `Bytes` constructor would still take two arguments.

Personally, I'm confused as to why this code is even running at all. As far as I can tell, nothing in the repo extends `Bytes` or otherwise calls `embedBytes()`.

**Comment by player-03** [comment]
Ok, I ran this for myself and tracked it down to [this line](https://github.com/HaxeFlixel/flixel/blob/e2c77730a892e21d9453e6c922d5c9c5b0699aa8/flixel/system/FlxAssets.hx#L34). There's nothing wrong with this line, it just extends `ByteArrayData`, and it's OpenFL's responsibility to make sure you can do that.

The thing is, both `ByteArrayData` and its parent class `Bytes` have an `@:autoBuild` tag, the former running `embedByteArray()` and the latter running `embedBytes()`. Therefore, anything that extends `ByteArrayData` gets both.

But that isn't ok. The `ByteArrayData` constructor takes one argument, whereas the `Bytes` constructor takes two (usually). If you call `embedBytes()`, it will pass two arguments to the superclass constructor, so that superclass had better not be `ByteArrayData`. It's possible that Haxe 4 had a bug preventing `embedBytes()` from getting called on `ByteArrayData` subclasses, but that's not something we'd want to rely on. [Per the documentation](https://haxe.org/manual/macro-auto-build.html), "It is important to keep in mind that the order of these macro executions is undefined."

**Comment by player-03** [comment]
Try my PR, and see if that fixes it for you.

**Comment by TechnikTil** [comment]
that fixes it, thank you!
