### ISSUE TITLE
Suggestion for keyboard input handling

### ISSUE THREAD

**Issue by initialize** [openfl/lime#237]
**Pre-emptive disclaimer**: First time poking around in the actual Lime code. I have no idea what I'm doing there. I base the suggestion below on my impressions from trying to figure out selected parts of the code. Please look at pictures of cute cats before proceeding. 

**Problem**: Trying to make unicode input work on Android keyboard input. Keyboard input in MainView.java handles only single byte input and does strange and mysterious conversion for the ancient ASCII set only. 

There is a kind-of-working workaround here http://www.openfl.org/archive/community/general-discussion/patch-for-non-ascii-character-input-from-soft-keyboard-in-androi/, but it only works for TextFields for some reason I don't know. KeyboardEvents are still defect for me when trying to extract charCode. 

**Suggestion**: Instead of treating keyboard input and special keys equally as keycodes, separate handling for special keys and text input. Handle keyboard input as unicode encoded characters uniformly regardless the platform. The responsibility for platform specific code is to receive input and pass it on in unicode or keycodes respectively. 

**Android specific suggestion**: Would it be possible to use a hidden TextView and capture input? Then you could pass on directives to the keyboard, like to enable auto correct which for some reason is only available when keyboard is invoked from a TextView.

**Comment by jgranick** [comment]
Yes, this is the plan :smile:

SDL2 moved to separate text input events, this requires special handling that goes directly into a TextField (or similar class) rather than flowing through as key events.

I'd be happy to discuss this more in the OpenFL Slack (can send an invite) or elsewhere, it's on the TODO list. I'm going to close this, though, as I'm trying to weed out TODOs so that bugs can be seen more easily here.

Thank you so much! :smile:
