### ISSUE TITLE
Latest Lime 2.0.0-alpha6 doesn't render text on Android

### ISSUE THREAD

**Issue by lmartinking** [openfl/lime#256]
I've just updated my OpenFL to 2.1.4 and Lime to 2.0.0-alpha6, now text rendering is broken in Android.
Previously I was using OpenFL 2.1.3 and Lime-2.0.0-alpha. Downgrading my Lime build appears to solved the issue.

I'm not able to give a really detailed report, but I am using HaxeFlixel and all FlxText no longer appears.

Update: Issue is still present on alpha 5, but alpha 2, 3 and 4 are okay.

**Comment by mbalestrini** [comment]
I don't think it's a Flixel-specific issue (I don't use Flixel). I think is something that happens when you embed fonts with **@:font** and then use **Font.registerFont**
In my previous comment there's some explanation of the tests I've done, to try to give you some clue.

Basically, if you change Main.hx of AddingText for this code, text doesn't render on android. You have to click several times for the text to appear, and trace(font.fontName) always returns garbage:

```
package;

import flash.display.Sprite;
import flash.text.Font;
import flash.text.TextField;
import flash.text.TextFormat;
import openfl.Assets;

@:font("assets/KatamotzIkasi-2.ttf") class EmeddedFont extends Font {}

class Main extends Sprite {	
	public function new () {		
		super ();
		stage.addEventListener(flash.events.MouseEvent.CLICK, function (event:flash.events.MouseEvent) {			
			Font.registerFont (EmeddedFont);
			var font = new EmeddedFont ();
			// var font = Assets.getFont("assets/KatamotzIkasi-2.ttf");
			var format = new TextFormat (font.fontName, 30, 0x7A0026);
			var textField = new TextField ();
			trace(font.fontName);
			
			textField.defaultTextFormat = format;
			textField.embedFonts = true;
			textField.selectable = false;			
			textField.x = 50;
			textField.y = 50;
			textField.width = 200;			
			textField.text = "Hello World";			
			addChild (textField);
		});		
	}
}
```

**Comment by kevinresol** [comment]
This have to be reopened I suppose....

**Comment by jgranick** [comment]
This is working for me, but maybe it was related to a later commit

**Comment by jgranick** [comment]
I just needed to make sure that I used a path that existed, for example, I copied the font file to "KatamotzIkasi-2.ttf" (outside the Assets directory, to be sure it wasn't using the copied file reference) and used that for the path. If it is in the Assets directory, it should be capitalized since the Haxe macros use exact file paths, not "rename" paths from the XML

**Comment by ubald** [comment]
I started having problems on cpp/mac with some fonts at specific sizes and just setting embedFonts to false got rid of my problems. I know it's not a solution but maybe a clue as to what is going on deeper inside of lime.

**Comment by jgranick** [comment]
I recently pulled a new TextField implementation from the NME project, perhaps that fixed it (or it was still font related), it used to use the "renderBitmap" C++ call to render, but now uses drawTiles internally, which fixed rotation and maybe this type of issue

**Comment by mbalestrini** [comment]
Still happening to me with:
hxcpp: 3.1.39 [3.1.48]
hxlibc: [1.1.4]
hxtools: [1.1.6]
lime-tools: 1.3.2 [1.5.7]
lime: 0.9.6 1.0.1 2.0.0 2.0.0-alpha.7 2.0.0-alpha.8 2.0.0-beta 2.0.4 [2.0.5]
nme-dev: [1.3.5]
nme: [5.2.13]
openfl-native: 1.3.0 [1.4.0]
openfl: 1.3.0 2.1.5 2.1.6 2.2.1 [2.2.3]

I tested it on a Samsung Galaxy Note 10.1 2014 and Galaxy S2.

Here's my sample project with font embedding if anyone wants to try it. The idea is that the text should appear once you click on the screen the first time. On some rare cases that happens, but normally you have to click a lot of times before the text appears (remember to close the app between tries). Also, if you test it with "lime test....", you can see on the console output that every time you click, instead of seeing the name of the font, this kind of string gets printed: ????????????楳
Sample project: http://www.videogamo.com/tmp/AddingText-embed.zip

**Comment by DanielUranga** [comment]
Im getting this issue too on latest Lime + Openfl from haxelib. fontName prints "????????????󇉡????????????󆺐????"

**Comment by jgranick** [comment]
@DanielUranga Does the same font work on the desktop? Is it all fonts, or only a specific one that has this behavior?

**Comment by DanielUranga** [comment]
Same font works on desktop. The problem occurs when using StablexUI with the Android4 theme, or when trying to load a custom ttf with the @:font metadata + fontName.

Using font "Arial" works both in desktop and Android.

Related: https://github.com/RealyUniqueName/StablexUI/issues/176
