### ISSUE TITLE
HTML5 WebGL CopyPixels

### ISSUE THREAD

**Issue by starburst997** [openfl/lime#282]
Using CopyPixels (transparent BitmapData) in WebGL results in edge around shape becoming darker and darker on each subsequent call (on part of the image not affected by the CopyPixels)

**Comment by jgranick** [comment]
I have a feeling this issue is occurring in the OpenFL WebGL renderer, not in Lime. I think the Lime level for copyPixels is fairly straightforward -- but this sounds like (perhaps) the OpenFL renderer is mistakenly pre-multiplying the image multiple times, when it should not be.

Would you mind opening an issue on the OpenFL tracker, and is there any way you could come up with a little sample that reproduces it, so I can be sure I'm looking at the same thing you are? Thank you so much!

**Comment by starburst997** [comment]
https://github.com/openfl/openfl/issues/515
