### ISSUE TITLE
Instanced rendering?

### ISSUE THREAD

**Issue by dmitryhryppa** [openfl/lime#316]
Hi!
Is there api in lime-next, to make instanced rendering on desktop targets? 
glDrawArrayInstanced?
glDrawElementsInstanced?

**Comment by jgranick** [comment]
So far, we have been following the WebGL specification for supporting the GL render API, by following WebGL, we can implement the same behavior on all GL targets (WebGL, GLES and desktop OpenGL)

However, I think that in order to allow better support for certain features beyond this initial set, perhaps we should look at considering support for WebGL 2 APIs, but we'll have to decide how we handle the two in a good way. I don't want to provide code completion for functions that are sure to break in many targets, so this is one we'll have to think out.

It looks like WebGL 2.0 is planned to have draw instance support:

https://www.khronos.org/registry/webgl/specs/latest/2.0/

**Comment by dmitryhryppa** [comment]
@jgranick , so when webgl 2.0 will be released, than it will be possible in lime, is it correct?

Hm... Just  interesting, is it possible to make extension for lime (and/or openfl openglview) with supporting desktop-like GL functions? I mean it as not a part of the base part of lime.

Sorry for my English, hope you understand what I trying to say :)

**Comment by jgranick** [comment]
I think we should design some way to expose WebGL 1 and WebGL 2 style APIs, and to allow the developer to switch (with the knowledge this might not work on older systems)

I'm going to close this, as I'm closing TODO items on the issue tracker (I'd rather not track them as defects for now) but happy to discuss this more on the OpenFL Slack (I can send an invite) or elsewhere

Thank you! :smile:
