### ISSUE TITLE
haxelib dev library not found

### ISSUE THREAD

**Issue by eliasku** [openfl/lime#319]
I install my dev library with `haxelib dev rage rage`, haxelib points to correct library path, but in project.xml I point it `<haxelib name="rage" />` and lime tools tell me `Error: Could not find haxelib "rage", does it need to be installed?`

What I've done wrong? Seems it happens after lime update... Help!

**Comment by jgranick** [comment]
Try running `haxelib path rage`, does it work?

You might have a problem with a haxelib that exists, but is missing standard ndll directories (if you have an ndll directory in your project), haxelib expects "Windows", "Mac", "Mac64", "Linux" and "Linux64" to exist for `haxelib path` to return properly, or otherwise, see what the command returns

**Comment by eliasku** [comment]
awww!! works! just forgot to install dev-dependencies :)) thank you for explanations and `haxelib path` trick!
