### ISSUE TITLE
issue running html5 with examples - errors

### ISSUE THREAD

**Issue by lewislepton** [openfl/lime#438]
hello,

as said, im running into trouble with lime running html5, just with a working HAXE/OPENFL game, just pong really.
but on running in thorugh terminal or even sublime it spits out errors. showing operation permitted stuff. how can i permit it.

probably a simple question, but need to ask

```
lepton:FRONG lepton$ lime test html5
chmod: Unable to change file mode on /usr/lib/haxelib/lime/2,4,0/templates/bin/node/node-mac: Operation not permitted
sh: /usr/lib/haxelib/lime/2,4,0/templates/bin/node/node-mac: Permission denied
lepton:FRONG lepton$ 
```

**Comment by lewislepton** [comment]
anyone?

just not thinking of a way to fix this. but maybe thats because ive been looking at it too long an d not seeing answers

thanks

**Comment by jgranick** [comment]
This must be due to the permissions level of your haxelib directory, this might be caused by installing using Homebrew or some other non-official install.

We should still consider using our own installer to help nail down these types of issues, but for now, setting the permissions yourself (`sudo chmod -R 777 /usr/lib/haxelib` or using the standard haxelib path ("/usr/lib/haxe/lib") should probably do it

**Comment by JesseTG** [comment]
I still have this issue.  Surely there's a better way than just haphazardly `chmod`'ing like this?
