### ISSUE TITLE
Font locating/loading problem on Archlinux [lime 2.4.9, openfl 3.1.3]

### ISSUE THREAD

**Issue by LaurentTreguier** [openfl/lime#503]
I'm having a weird problem. I tried using a simple OpenFL TextField (that's all the program does) compiled either into Neko or C++ and there was no text rendered. It was on Linux. I then tried on Windows and on Android, and on those OSes it worked, I could see the text rendered. My Linux is an Archlinux. I thought that lime would be tested on Ubuntu as it's the most widely used Linux distribution, and thus tried my simple program on Ubuntu 15.04... and it the text showed up correctly.
I began to wonder about font directories. It seems the default font used by TextField is Times New Roman, and the font directory used by lime is `/usr/share/fonts/truetype` on Linux (seen [here](https://github.com/openfl/lime/blob/master/project/src/backend/sdl/SDLSystem.cpp#L132)). On Archlinux, the main fonts and Times new Roman are located in `/usr/share/fonts/TTF`, while on Ubuntu the main fonts are located in`/usr/share/fonts/truetype`. I thought that it was the problem. However, on Ubuntu, there is no Times New Roman. The font just isn't there, but the program still runs fine and shows the text in the TextField. On the other hand, on Archlinux, I tried making a `/usr/share/fonts/truetype` directory with all the fonts from `/usr/share/fonts/TTF` inside, but still no text in the TextField...
When manually loading a font located in the assets directory it always works however. The problem is with the default font only.

What could go wrong other than locating the font ?

**Comment by Hasufel** [comment]
see https://github.com/openfl/lime/issues/392 ?

**Comment by jgranick** [comment]
Perhaps we need to consider fonts as a special case. Instead of a system directory, we need a list of system paths. Either that, or we use a smarter system of detecting where the fonts are :wink:

https://github.com/openfl/lime/blob/master/lime/system/System.hx#L34

goes to:

https://github.com/openfl/lime/blob/master/project/src/backend/sdl/SDLSystem.cpp#L132

In OpenFL, the default font is actually "_serif" (similar to "_sans" or "_typewriter"), a special font name that looks for a default serif font for the system:

https://github.com/openfl/openfl/blob/a8c738938a339a77efb0e8b82edb9e40c26aafe3/openfl/_internal/renderer/cairo/CairoTextField.hx#L217

On Linux, we're looking for "FreeSans.ttf" at the moment.

**Comment by LaurentTreguier** [comment]
It seems like FreeSans.ttf isn't on Arch by default. I found no font that were installed on both systems right from the start :disappointed: ... I came across the "fc-match" shell utility. It's installed on both systems and fetches the best available font according to a pattern (for example : `fc-match serif` returns `DejaVuSerif.ttf: "DejaVu Serif" "Book"`). But that will probably just add unnecessary complexity, and creating a process using sys.io.Process will make a console pop on Windows...
Fonts can really be a mess on Linux. Perhaps the best solution would be to simply change the font directory and extend the font list ?

**Comment by neni** [comment]
No tff font on Archlinux by default (and no default install too).
package: https://www.archlinux.org/packages/extra/any/ttf-freefont/
file: /usr/share/fonts/TTF/FreeSans.ttf

**Comment by jgranick** [comment]
Is that package regularly installed?

Perhaps using "TTF" instead of "truetype" in the font path would do it, or perhaps we should use "/usr/share/fonts" only for the font system path, and append those to the font name we're looking for (search "truetype/freefont/FreeSerif.ttf", "TTF/FreeSans.ttf", etc)

Actually, now that I say it out loud, that seems just like what we need, what do you think?

**Comment by LaurentTreguier** [comment]
Moving the TTF/truetype part of the path is a good idea, but unfortunately, I fear that ttf-freefont isn't regularly installed, with all I have installed (and I can install loads of packages sometimes) I don't have it installed. Some fonts seem to be installed with Xorg, but they are PCF fonts and not TrueType fonts. Other than that, each graphical interface installs its own choice of fonts...

**Comment by jgranick** [comment]
I wonder if we should consider bundling some free fonts

Do you have other default sans or serif fonts installed, like Arial, or other common faces?

**Comment by neni** [comment]
ttf-freefont is not regularly installed. ttf-dejavu is most popular for the default ttf font. But 6 or 7 other fonts could replace it (ttf-dejavu, ttf-freefont, ttf-liberation, ttf-bitstream-vera, ttf-linux-libertine, ttf-droid, ttf-ubuntu-font-family, ttf-oxygen).

**Comment by LaurentTreguier** [comment]
I just realized I was worried about a console popping up on Windows, when the issue is on Linux... Silly me. Using sys.io.Process and fc-match it should be possible to get a usable font on absolutely any Linux distribution. If you type `fc-list | grep $(fc-match | cut -d: -f1) | cut -d: -f1` in a shell prompt, you should get the path to a font.

**Comment by larsiusprime** [comment]
I believe Vera Sans and Liberation sans are some good free fonts, for what it's worth. Vera is a "verdana-like" and Liberation is a "Helvetica-like" (Arial itself being a Helvetica-like).
