### ISSUE TITLE
Cross Origin Image - tainted canvas

### ISSUE THREAD

**Issue by urbananimal** [openfl/lime#558]
Affects HTML5 target - 

When trying to access the pixel data of an image loaded from a different domain (using openfl.display.Loader) I get - 

`Unable to get image data from canvas because the canvas has been tainted by
cross-origin data`

I've got it working in my project by adding 

`image.crossOrigin = "Anonymous";`

after

`var image = new JSImage ();`

in lime.graphics.Image.hx but I'm not sure if this is really a good thing to add as default. It should probably be an option passed in? If so it would need a corresponding change in openfl.

Mark

**Comment by jgranick** [comment]
Ah, very interesting.

Do you know if `crossOrigin = "Anonymous"` would hurt anything? Would there be images that come from a site without a cross-origin header, and it would fail to load instead of providing it in a "tainted" way? 

Either there's no down-side to including this (though you do need to set up the host domain to provide access) and we look at including it by default, or is there a hazard (or potential error) involved with using this, and we go into setting up the `LoaderContext` plus `checkPolicyFile` in order to add this property on HTML5

**Comment by urbananimal** [comment]
Well I think the downside is that it's a security issue? I'm not really sure how, it's not something that I've every looked into. You only need to set up the host if you're trying to access it from a different domain, adding the crossOrigin property doesn't affect images served from the same domain (not sure if this is what you were suggesting?).

The crossOrigin property isn't set by default in native html/js so I don't think it is something that should be set by default in lime/openfl. Using LoaderContext/checkPolicyFile to add it seems like the best solution to me.

**Comment by bobbybee** [comment]
This line causes all images on my machine to fail to load :confused: 
That said, I'm not sure this is a browser bug or a lime bug, as I believe other people running the identical code base have reported it to work, this line included.

Either way, thoughts?

**Comment by jgranick** [comment]
I believe this has been resolved in current builds, but if there is still trouble, we would be happy to discuss the problem more on Slack or the forums to determine a plan of action. Thank you :smile:
