### ISSUE TITLE
CFFI finalizer causes crash when GC occurs

### ISSUE THREAD

**Issue by vroad** [openfl/lime#577]
When GC callback is triggered with this future, there is no guarantee that all script objects finalizers are working with is still alive... and I don't think setting finalizer from script is a good idea. That will make things pretty complex.

For example, in JavaScript world, you cannot manually destroy any native object by yourself, to prevent script writers from crashing whole application or leaking resources.

I also want to hide pointers from script, which is currently stored as 64bit floating point value, though it seems impossible with current CFFI api.

**Comment by jgranick** [comment]
HXCPP has a "setFinalizer" API that allows Haxe-based finalizers. This is strictly HXCPP-only, and could lead to known memory leaks for Neko, Node.js, or future CFFI-compatible targets.

I was hoping to create a generic @:finalizer API that worked in Neko, C++, and hopefully Node.js. Cairo bindings (for example) return the actual object pointers with no wrapper, and abstract classes provide the related APIs. I like how transparent this is, but it breaks of possibility of using `val_gc` manually on the C++ side (which is a pain) and so I hoped to have some way of doing a simple Haxe-based finalizer to catch collection so we can `cairo.destroy ()`, etc.

The third option is no finalizer anywhere, but then we have to strictly destroy these objects, and may run into some real architecture headaches with not being able to allow automatic garbage collection, such as nullifying a BitmapData instead of calling `dispose ()`, which I really want to support

The only other solution I can think of is to register relevant BitmapData in a master list, and every frame, we check whether the data is still "active" and remove it from the list and force a destroy if it is not. It could catch some cases but still leads to unnecessary calls to new Cairo objects and is really uncomfortable

**Comment by vroad** [comment]
WebGL doesn't  support automatic GC of its resources either(textures, buffers, programs). Maybe because they are on VRAM instead of main memory, at least on most desktop computers. That may affect the process of GC.

Maybe we should give up releasing BitmapData automatically as well?

Even when you forget releasing textures or buffers, they will be released when WebGL context is collected by GC. (You cannot manually dispose WebGL context)

**Comment by vroad** [comment]
I don't find any good point about storing pointer as a raw value, and making it visible to script. There is alloc_abstract for that, right?

Actually I didn't know that alloc_abstract was added to API for storing native objects. (So I wrapped pointer in a object, in my fork.) It's already used in hxcpp's standard library. It's safer to store native pointer in them than in float value, works on all targets, always passed by reference, and you can set GC callbacks (which is not possible for float value).

To be able to delete BitmapData on GC, I also think that you need to keep track the list of all BitmapData, but do you really need to check "every frame" whether they are still alive?

Instead of that, you could set gc callback as usual to BitmapData and when GC callback is triggered, call delete and nullify abstract in C++, then you can delete it from the list.

If you need to delete BitmapData's parent (cairo in this case), you can delete and nullify abstract in C++, same as above. Then delete entire list.

**Comment by vroad** [comment]
I'm not sure whether you can unset GC callback when it's no longer needed.
It does not trigger GC callback for already deleted abstract, maybe. If so you don't need to unset GC callback.

**Comment by vroad** [comment]
Recent version of lime is using CFFIPointer structure now, and now not using @:finalizer anymore. We can close this issue now?

I think that there are still memory leaks in spite of this, because virtual destructor is not defined for most classes in C++. Also, many AutoGCRoot pointers and some library handles are not released at all.
