### ISSUE TITLE
lime build requires lime

### ISSUE THREAD

**Issue by bjitivo** [openfl/lime#620]
Self-dependencies in build tools is one of the more ridiculous things I have encountered in my development career.  Please stop making build tools that require themselves to exist before they can be built.

**Comment by jgranick** [comment]
hey @bjitivo, hope all is well :smile:

What are you trying to build? Tools? Binaries? A project?

The tools can be built using `haxe build.hxml` in the "lime/tools" directory if you prefer. If you run `haxelib run lime`, it should build the tools, though, if they are not present.

Older of versions of the Lime tools required Lime binaries to operate, but most of the time, Lime tools no longer require binaries now (except for things like image processing, such as generating icon files). They imply `-nocffi` when running.

If you are more specific, maybe I can help more? Thanks!

**Comment by bjitivo** [comment]
OK sorry about my curtness.  It was a frustrating day.

If what you say is true, then this is great news.  I was expecting the lime haxelib to depend upon lime because I briefly looked at one of the files (RunScript.hx?  Not sure) and saw that it ran lime, which made me believe that the tool still needed itself to run.

Sorry again for the noise.

**Comment by jgranick** [comment]
Ah, RunScript. That builds the "run.n" file which we include (already compiled) on the repository, in order to forward commands so `haxelib run lime` (for example) works out-of-the-box and doesn't require a manual `haxe build.hxml` command.

You may know that we build Lime nowadays on a build server -- things have improved!

I just checked, here are the commands we use on TeamCity (for example) for Linux binaries:

```
export HAXELIB_PATH="%system.teamcity.build.workingDir%"

haxelib dev lime lime
haxelib install format
haxelib install hxcpp

lime rebuild tools -nocolor -verbose

lime rebuild linux -64 -release -verbose -nocolor
lime rebuild linux -32 -release -verbose -nocolor
lime rebuild linux -64 -Dlegacy -release -verbose -nocolor
lime rebuild linux -32 -Dlegacy -release -verbose -nocolor
```

The `lime` command is installed on our build servers, but `haxelib run lime` would work too.
