### ISSUE TITLE
Angle?

### ISSUE THREAD

**Issue by jobs-git** [openfl/lime#634]
What is angle for @larsiusprime, how does it work :)

**Comment by larsiusprime** [comment]
@jobs-git ANGLE is google's "Almost Native Graphics Layer Engine."

In short, it wraps an OpenGL API around DirectX calls. DirectX is much better supported on Windows than OpenGL, so ANGLE lets you take an existing OpenGL project, like Lime, and make it use DirectX if you want, in order to ensure wider compatibility.

**Comment by jobs-git** [comment]
that means when an App is OpenGL ready it is also DirectX ready?

**Comment by larsiusprime** [comment]
More or less. We're still working out the kinks.

**Comment by madrazo** [comment]
@larsiusprime @jobs-git I wonder if Angle is compatible with Universal Apps (UWP) to target Xbox One ;) https://github.com/HaxeFoundation/hxcpp/pull/336

**Comment by larsiusprime** [comment]
@madrazo I'm not sure! It would be cool if true.
