### ISSUE TITLE
Window.width inconcistency

### ISSUE THREAD

**Issue by NekR** [openfl/lime#645]
On iOS and OS X with Retina displays `Lib.application.window.width` reports DPI scaled value, e.g. if window was requested with value `800` it will report `800` on Retina display too, while `stage.stageWidth` will be `1600` (real size in pixels). Another example is iPad (landscape), where `window.width` is `1024` and `stage.stageWidth` is 2048.

However, Android behaves differently here and reports `window.width` in device pixels, e.g. on device with `1280` width,  both `window.width` and `stage.stageWidth` have `1280` size.

I think Android also should report `window.width` as `stage.stageWidth / DPIDensity`. This is particularly useful when you need to get window/screen DPI in app code to property scale, hm, everything.

**Comment by jgranick** [comment]
This is currently based on what we receive from SDL. When they modified the support for "high DPI" display on iOS, it (effectively) broke window resize as well as mouse event coordinates, based on logical "points" rather than pixels. This is not the behavior on Android, though I believe SDL may include the high DPI behavior on Windows or OS X.

In the future, the way SDL handles Android may look more like iOS, but its hard to say. In the meantime, I recommend handling `window.width * window.scale` if you use Lime directly :smile:

**Comment by NekR** [comment]
Thanks for the info @jgranick! I didn't know about `window.scale` property.

Just tried and it seems to work fine and as I want, except that on Android CyanogenMod it still reports `scale = 1`, while on device it's about `3`. It seems like a this issue https://github.com/openfl/lime/issues/369, but as I understand scale is calculate like this `outerWidth / width`, so it should be correct if SDL has correct `width`.
