### ISSUE TITLE
default Android SDK 19 too high?

### ISSUE THREAD

**Issue by xmorpher** [openfl/lime#683]
Just an opinion... According to my stats, about 40% of users have devices with API lower than 19, 
the "immersive mode" is really that important/necessary to discard 40% of devices?
I know you can set default lower than that in the project.xml, 
but will it work ok on android or will crash if the project uses a lower Api?

**Comment by jgranick** [comment]
We use Android API 19 as the "target SDK", but I believe API 10 is our "minimum SDK". This means the newer SDK to compile (to take advantage of newer features) but we should be designed so that older platform versions will still run, without the newer behavior.

Practically, it means that things like immersive mode just won't happen on an older platform, but it should hide the button graphics with the fade-out effect.

So we should be compatible with 99% of devices or so

**Comment by xmorpher** [comment]
nice. thanks!
