### ISSUE TITLE
HTML5, canvas: focused TextField steals focus when clicking outside the canvas

### ISSUE THREAD

**Issue by bendmorris** [openfl/lime#695]
Using OpenFL. If I set focus on a TextField and then click on a text input in another part of the page external to the OpenFL canvas, the TextField will steal focus back almost immediately. If I first click outside the TextField but within the OpenFL canvas to remove focus from the TextField, and then click on the external text input, this doesn't happen.

Commenting out this line in HTML5Window.hx seems to prevent the focus stealing:

```
private function handleFocusEvent (event:FocusEvent):Void {
    if (enableTextEvents) {
        //Timer.delay (function () { textInput.focus (); }, 20);
    }
}
```

...but this preserves a flashing cursor in the textbox after it loses focus.

This happens in Chrome, Firefox and Safari; additionally, in Firefox clicking anywhere while a TextField has focus will cause the page will jump back up to the OpenFL canvas if you've scrolled away from it.

**Comment by jgranick** [comment]
I'd like to know if focus has gone inside or outside of our parent `element` in order to handle the behavior, but `focus`, `blur` (which don't bubble, which makes sense) and `focusin`, `focusout` (which is supposed to bubble) don't appear to work, listening only to `element`.

For now, I've tried to make a solution that tries to preserve the same behavior (where a related DOM element that steals focus which is not intended to halt text input) while making it allow focus to go to unrelated elements. We might have to go so far as making every DOM element that's related have focus/blur events (to make this more elegant), but I hope not
