### ISSUE TITLE
Migrate to an instance-based GL implementation to better support multiple contexts

### ISSUE THREAD

**Issue by jgranick** [openfl/lime#788]

**Comment by vroad** [comment]
I already have C++/Haxe callses that do this. What do you think about it?

https://github.com/vroad/lime/blob/cfa6e6cebd0e569e6f98a2af60ab85cf583a0048/project/src/graphics/opengl/GLContext.cpp#L158-L168
https://github.com/vroad/lime/blob/2cb7c81d470262ed5e3f8b2432ad40fe0c2b53cc/project/src/utils/ArrayBufferView.cpp

It automatically

1. Make context current if it's not already current (throw exception and returnr if you try to use an invalid context)
2. Check if it has GL objects to delete
3. Call OpenGL function

I chose this pattern because it requires fewer number of C++ calls compared to calling this from a Haxe wrapper class. It also makes multi-threading support easier because you don't need to store GL context in `static var` . If you want to save current context, you could do that by myself.

It no longer deletes OpenGL resources as soon as they are deleted by GC. It pushes collected resources to a queue first and delete them when next OpenGL call is used. I did this because I don't think checking if queue is empty has big overhead, and this solves problems with C# finalizer, which does finalization in its own thread. I don't want users to call `checkQueue()` explicitly, or push context instance to the timer class. (How can I do that beautifully if multiple threads are involved?)
