### ISSUE TITLE
Linux package manager

### ISSUE THREAD

**Issue by ibilon** [openfl/lime#804]
After https://github.com/openfl/lime/pull/801 

We need to refactor this code to better support more package managers and also make a list of the one we need to add.
Maybe by distribution(/version) instead of packager name since we can figure out the name from the version and packages name (or packages, like `ia32-libs-multiarch`) can change.
- openSUSE: zypper

**Comment by skwerlman** [comment]
Potentially of note: https://en.wikipedia.org/wiki/List_of_software_package_management_systems#Linux

**Comment by mtelesha** [comment]
I was installing Haxe for the first time and ran `lime setup Linux` on my OpenSUSE machine.

OS: OpenSUSE Leap 42.1

Issue:  `lime setup Linux` 

Error: uncaught exemption Error running: sudo apt-get install

This limits me to actually running lime on anything besides Debian based systems.

Issues can also arise due to different package names and versions on different distros. Would be great if there could be an appimage, flatpak or container for Linux for Haxe.

**Comment by liminalitythree** [comment]
note that his doesn't work on the newest LTS version of ubuntu either, the package name has changed to `ia32-libs`.

or at least `ia32-libs-multiarch` isn't available on my system.

is there a page somewhere that shows the dependencies of the linux build? I wouldn't mind installing them manually, but it's annoying that I can't build for native platforms just because the tool has a hardcoded setup command.
