### ISSUE TITLE
Export to iOS : Uncaught exception - std@file_full_path

### ISSUE THREAD

**Issue by Paul-Ollivier** [openfl/lime#829]
when calling $ openfl test html5 in my project folder, everything exports fine, but when selecting iOS as a target i get the following exception :

Called from ? line 1
Called from CommandLineTools.hx line 1431
Called from CommandLineTools.hx line 25
Called from a C function
Called from CommandLineTools.hx line 126
Called from CommandLineTools.hx line 640
Called from lime/project/PlatformTarget.hx line 120
Called from lime/tools/platforms/IOSPlatform.hx line 378
Called from lime/tools/helpers/IOSHelper.hx line 284
Called from /usr/lib/haxe/std/neko/_std/sys/FileSystem.hx line 50
Uncaught exception - std@file_full_path

Exporting for iOS works usually fine though, when i test it with other example projects for instance.

I might have screwed up some settings in my project.xml maybe? Could use some help here! :}

**Comment by jgranick** [comment]
I don't see any reason why it would not work properly, unless the build did not actually complete, and this error occurs because the target directory never was created. You said other samples worked for you, though?

There are multiple iOS-related improvements in the GIT version of Lime that may help, are you able to test development builds?
