### ISSUE TITLE
lime setup android crushing

### ISSUE THREAD

**Issue by NexiePrado** [openfl/lime#831]
Hello, everyone!

I just trying to setup android for lime. I have runned command "lime setup android", but it crashed with error:

> Called from ? line 1
> Called from CommandLineTools.hx line 1431
> Called from CommandLineTools.hx line 25
> Called from CommandLineTools.hx line 94
> Called from CommandLineTools.hx line 1446
> Called from utils/PlatformSetup.hx line 407
> Called from utils/PlatformSetup.hx line 417
> Called from utils/PlatformSetup.hx line 836
> Called from utils/PlatformSetup.hx line 238
> Called from haxe/zip/Reader.hx line 194
> Called from /usr/lib/haxe/std/haxe/io/Bytes.hx line 457
> Uncaught exception - alloc.c(180) : out of memory

Thank's!

**Comment by ibilon** [comment]
Looks like the zip contains a file which is too big to fit in your memory,
how much RAM do you have?
What zip was it trying to install?

**Comment by NexiePrado** [comment]
I have 3Gb RAM, x64 Windows
Android NDK zip

**Comment by mgalpy** [comment]
i'm getting the same problem in widows x64, 12 Gb ram... processes wasn't taking up more than 2 Gb

**Comment by nykevinwong** [comment]
I got the same issue. I have 4 GB RAM on Windows 7.
would it be possible to access an installed Image ISO on a mounted folder/drive instead of downloading file by file?

  Created toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/libexec/g
cc/
  Created toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/libexec/g
cc/arm-linux-androideabi/
  Created toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/libexec/g
cc/arm-linux-androideabi/4.9/
  Install toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/libexec/g
cc/arm-linux-androideabi/4.9/libfunction_reordering_plugin-0.dll
  Install toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/libexec/g
cc/arm-linux-androideabi/4.9/cc1plus.exe
Called from ? line 1
Called from CommandLineTools.hx line 1569
Called from CommandLineTools.hx line 24
Called from CommandLineTools.hx line 99
Called from CommandLineTools.hx line 1584
Called from utils/PlatformSetup.hx line 407
Called from utils/PlatformSetup.hx line 417
Called from utils/PlatformSetup.hx line 836
Called from utils/PlatformSetup.hx line 238
Called from haxe/zip/Reader.hx line 194
Called from /usr/lib/haxe/std/haxe/io/Bytes.hx line 457
Uncaught exception - alloc.c(180) : out of memory

C:\DEV\haxe>

**Comment by jgranick** [comment]
Tracking here https://github.com/openfl/lime/issues/878

**Comment by Cleod9** [comment]
@nykevinwong Your issue looks similar to mine, where it would crash during toolchain installation (I assume that is also probably what @NexiePrado was seeing). I solved this by downloading the [NDK manually](https://developer.android.com/ndk/downloads/index.html) and extracting its contents to the Android NDK folder myself. It didn't even need to "install" anything, I just did a basic extract wit the unzip command on my CLI.

For what it's worth I also use Windows 7, 16GB of RAM, and my educated guess is that the lime command line tools just can't handle the size of the NDK archive

**Comment by Binklebonk** [comment]
Same issue here on Windows 10 x64, 8GB RAM.

> Called from haxe/io/Bytes.hx line 474
> Uncaught exception - alloc.c(180) : out of memory

By manually downloading and unzipping the required version of Android NDK (r13 in my case), then directing **lime setup android** to it, the issue was circumvented.
