### ISSUE TITLE
HXP support broken (command line too long)

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#903]
I can't get projects with HXP project files to work at all anymore (using Lime 3.6.0, Windows 10). This means that even with a completely empty `Project.hxp` file:

```haxe
class Project extends lime.project.HXProject {}
```

...running `lime build <target>` ends with "Command line is too long".

Running a `-verbose` build reveals that the command line seems to contain my entire `PATH`, which is indeed quite long on this system.

**Comment by Yanrishatum** [comment]
I've managed to make a temporary fix, but it does not compatible with current helper of Lime. Thing is, Lime passes all environmental variables via command line. I've changed it from passing them via command line to passing them via `stdin`.
Pros:
* Do work.
* Do not bloat command line

Cons:
* Output from HXP process do not printed to console (unless you read the `stdout`/`srderr` of process manually)

1. Instead of data, I pass the String length of that data via arguments.
2. In `main()` after argument count check: 
```haxe
    for (i in 0...args.length)
    {
      args[i] = Sys.stdin().readString(Std.parseInt(args[i]));
    }
```
2. Instead of calling `ProcessHelper.runCommand("", "neko", ...)` I used custom code in `fromFile` function:
```haxe

    var argList:Array<String> = [HXProject._command, name, 
      Std.string (HXProject._target), Std.string (HXProject._debug), Serializer.run (HXProject._targetFlags), 
      Serializer.run (HXProject._templatePaths), Serializer.run (HXProject._userDefines), Serializer.run (HXProject._environment), temporaryFile];
    var nekoArgList:Array<String> = [for (a in argList) Std.string(a.length)];
    nekoArgList.unshift(FileSystem.fullPath(nekoOutput));
    var p:Process = new Process("neko", nekoArgList);
    for (arg in argList)
    {
      p.stdin.writeString(arg);
    }
    var code:Int = p.exitCode();
    p.close();
```
Quite simple, but there is room for improvement.
