### ISSUE TITLE
Add support for limiting the number of active HTTPRequest objects

### ISSUE THREAD

**Issue by jgranick** [openfl/lime#942]
Too many requests can begin to fail on HTML5, or hurt performance on native, so we should add support for setting a maximum number of simultaneous requests

**Comment by mastef** [comment]
I guess this was related to d593685dcb12ac7fee79cf41119bfa84b99b6eb7 and http://community.openfl.org/t/openfl-4-8-1-preloader-error-load-assets-cause-stopping-loading-at-html5/8832

Not sure it's a good idea to throttle assets for all browser out there, especially since now with http/2 we can load up to 100 assets at the same time.

**Comment by mastef** [comment]
I think the issue that the original posters had happened when loading 400-500 assets at the same time. Increasing the `private static var requestLimit = 4;` from 4 to a much higher value should be relatively safe. Or making it `public`, so it can be overridden - could also be an OK solution.

4 seems to be a very low value. When hacking this to a value of 50+ then an assets heavy game significantly decreases load-times ( e.g. when opening a shop popup that loads its own assets ). Until now I was wondering why so many assets were slowly loading in sync, instead of async.

**Comment by mastef** [comment]
Changing https://github.com/openfl/lime/blob/develop/lime/_backend/html5/HTML5HTTPRequest.hx#L32 to : 
```
-       private static var requestLimit = 4;
+       public static var requestLimit = 4;
```

And then defining `lime._backend.html5.HTML5HTTPRequest.requestLimit = 100;` in the app had the following impact on an asset heavy html5 game ( both loads with cache disabled ) : 

![before](https://user-images.githubusercontent.com/762297/35789719-97f30e70-0a70-11e8-863d-bce81072e282.png)
![after](https://user-images.githubusercontent.com/762297/35789720-982b01ea-0a70-11e8-87c4-992ed2d347a2.png)

That's ~40 seconds vs ~80 seconds.
