### ISSUE TITLE
BunnyMark compilation time increased x2 in 3.7.4 -> 4.0.0 switch

### ISSUE THREAD

**Issue by infidel-** [openfl/lime#948]
Looking about the separate openfl compilation speed problem I've noticed that lime got worse too when the version changed from 3.7.4 to 4.0.0. In general it was 1 second, now it's 2 seconds. May not sound like a lot but this is worse in larger projects, however, since I don't have a lime-only project, this is compounded by openfl on top of it (and maybe other frameworks). But still, I think that deserves some investigation.

Here are the test results. Haxe 3.2.1 was used due to the latest 3.4.2 having problems with macros in the compilation server.

```
lime create BunnyMark
```

lime 3.7.4:
```
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.64
user 0.58
sys 0.41
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 0.86
user 0.29
sys 0.34
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 0.95
user 0.34
sys 0.37
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 0.90
user 0.33
sys 0.36
```
2.6s->0.9s

lime 4.0.0:
```
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 3.94
user 0.59
sys 0.44
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.26
user 0.42
sys 0.26
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.36
user 0.41
sys 0.31
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 1.90
user 0.35
sys 0.34
```
4s ->2s

Latest release (the problem persists) (lime 4.0.3):
```
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 3.87
user 0.61
sys 0.42
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.15
user 0.38
sys 0.30
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.36
user 0.38
sys 0.28
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 1.88
user 0.40
sys 0.24
```
4s->2s

**Comment by jgranick** [comment]
I found a major cause of slowdown between versions

Using Lime 3.5.0 with the older BunnyMark sample, I was receiving 1.65 second build times with Neko on the system I'm using now, but with development versions it was jumping to 2.76 seconds, a 67% increase in time.

I removed an import of `lime.graphics.ImageBuffer` in one the asset macro, which reduced the build time to approximately 1.95 seconds, or 18% slower.

It is difficult to determine if the remaining differences are caused by another macro, or if it is related to additional features added to the code (such as release build behavior in core Lime classes on C++, or how these two versions of BunnyMark use different forms of OpenGL bindings)

https://github.com/openfl/lime/commit/ead9ed12737e2183f5a2940c351be05c6cf389ab

Could you test with this change, and see how it performs for you?

Thank you

**Comment by infidel-** [comment]
Looks to be fine now, thanks.

lime 3.5.0:
```
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.59
user 0.40
sys 0.32
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 1.02
user 0.45
sys 0.36
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 1.02
user 0.46
sys 0.30
```

lime 4.0.3 + patch
```
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 2.41
user 0.47
sys 0.28
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 1.05
user 0.46
sys 0.26
infidel@purplestar ~/p/BunnyMark> time -p lime build project.xml html5 --connect 6000
real 1.00
user 0.36
sys 0.34
```
