### ISSUE TITLE
`lime help` is missing the `-final` argument

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#996]
`lime help` (as of Lime 5.1.0) doesn't contain any information about the `-final` argument. Ideally, it should mention what exactly it does. I know that on HTML5, it does minification and enables DCE=full, but:

- does it enable dce on other targets as well?
- does it use Google Closure or YUI?
- does it do anything else?

**Comment by jgranick** [comment]
Thanks

I've added a mention in the `lime help` output. We need more documentation in general, the website should include more detail about the difference between debug, release and final release build configurations

Yes, it implies DCE and minification on HTML5, but its also a distinct build configuration, similar to `#if debug` and I think `#if release` (would have to check if that's present right now?)

The goal is to do things that make for a better release, even if its a slow build. We could consider additional compiler optimizations on C++ targets, or other features. DCE on all platforms is maybe overkill, since it's usually performance on native, and not file-size, that's a greater concern

**Comment by Gama11** [comment]
`-D analyzer-optimize` might be a good flag to add in Haxe 3.4.2+.

Would be nice if the command line help for `-final` had a bit of info what final actually _does_, as is it's not super helpful...

**Comment by jgranick** [comment]
The command-line help also doesn't tell us what the difference is between debug or release build configurations either. That's why I think we need more documentation elsewhere to go in more detail
